### ISSUE TITLE
Update for 5th anniversary 

### ISSUE THREAD

**Issue by islembta** [stuartaharrison/dbl-anniversary-qrcode-generator#1]
Demo is down and code doesn't work for 5th anniversary

**Comment by stuartaharrison** [comment]
Hi, thanks for the issue.

I normally take the site down after the anniversaries as nobody will be interested in the generator outside of the anniversary events.

I'm working on the update now as they have changed the encoding of the timestamp at the end of the code. I might release an update/temporary fix that would let you input the encoded section from your in-game QR Code to the end of the ones generated from the app.
